### ISSUE TITLE
Get CD benchmarks in? 

### ISSUE THREAD

**Issue by davidlmobley** [MobleyLab/benchmarksets#45]
@nhenriksen - we just got Germano's bromodomain stuff merged in, so would now be a good time for you to proceed towards getting your cyclodextrin stuff merged in as well? It seems like it will likely become important to do so fairly soon since it's potentially being used for the Yank paper (cc #41 ). Since we're done working on the bromodomain stuff now it should be possible to proceed towards merging without having to resolve conflicts multiple times.

Or, are there other things you need to do first?

**Comment by nhenriksen** [comment]
Yes, I'm finishing up some text about "previous studies" right now.  I've already got tables and figure updated.  Hoping to have something for us to start discussing by tonight.

**Comment by nhenriksen** [comment]
I've finished adding text, tables, references to the manuscript and merged in the latest changes from master (see f85a8ae1c9a4bb7a9c20f5a2da156bb905ddd6b1).  So it should be ready to start editing!

**Comment by davidlmobley** [comment]
@nhenriksen - can you open a [WIP] PR? I like to do edits/discuss changes on a PR which is open. :)
