### ISSUE TITLE
Typo in reference for Lysozyme L99A/M102Q - catechol experimental value?

### ISSUE THREAD

**Issue by andrrizzi** [MobleyLab/benchmarksets#63]
The reference for the binding free energy of catechol to T4 L99A/M102Q in Table VIII is indicated to be [[224](http://www.sciencedirect.com/science/article/pii/S0022283602007775)]. I took a look at the original paper to figure out buffer conditions, but I couldn't find a reference to ITC measurements with catechol (see Table 3 in [224]). Also, in the benchmark sets paper, catechol is the only compound coming from [224] with an error associated with the experimental binding free energy.

Is it possible that this is a typo? It could be that the value comes from [[19](http://www.sciencedirect.com/science/article/pii/S0022283609011760)] instead.

**Comment by davidlmobley** [comment]
It's very possible this is a typo. The value matches that in [19]?

Apologies, I somehow missed this when you submitted it.

**Comment by andrrizzi** [comment]
> It's very possible this is a typo. The value matches that in [19]?

Correct! However, I believe that the free energy for phenol used [19] was taken from [224] so I'm not 100% sure about its original provenience.

**Comment by davidlmobley** [comment]
Yes, you're right, @andrrizzi -- the value for catechol comes from [19]. That's why it's not listed in the Shoichet lab lysozyme take-aways page, as their spreadsheet has not been updated since this data was published.

I'll do a PR to correct. Thanks.
