### ISSUE TITLE
PDB files for BRD4 parameterized systems are missing CONECT records

### ISSUE THREAD

**Issue by jchodera** [MobleyLab/benchmarksets#70]
The `BRD4-*.pdb` files in [this directory](https://github.com/MobleyLab/benchmarksets/tree/master/input_files/BRD4/prmtop-coords) are missing the required `CONECT` records for the small molecule ligands.

As a result:
1. They are not even valid PDB files, which require `CONECT` records for nonstandard residues
2. They cannot be used to build parameterized molecular systems

**Comment by davidlmobley** [comment]
I believe these are from @GHeinzelmann who, I believe, used these with AMBER to set up his systems.

I realize the PDB format requires CONECT entries as part of the specification, but as you're well aware, not every toolkit conforms to the specs.

**Comment by jchodera** [comment]
It looks like `ambpdb -p BRD4-1.prmtop -c BRD4-1.crds -conect > BRD4-1.pdb` will create the PDB file with the correct `CONECT` records. I'll do this now and open a PR.
